### PR TITLE
Update logo and menu

### PR DESCRIPTION
**Pull request by allthatilk**
Update logo, add new navigation menu, update some old styles to be more in-keeping with new branding and fix style clashes with old branding that made some elements display weird.

### CODE REVIEW

**Comment by allthatilk** [comment]
Can't find a way to test the styling changes locally so marking as complete. We can look into maybe spinning up a clone of the current site to test them or something next week.

**Comment by allthatilk** [comment]
Awaiting favicon changes to pattern lib

**Comment by dalepotter** [comment]
Just generated the site locally - this is how the homepage looks for me 

:-(

image

**Comment by allthatilk** [comment]
The styles should pull in now. Still likely to look weird as I had to make the changes blind.

**Comment by allthatilk** [comment]
Different approach taken that was more minimal due to style conflicts. Closing PR.

**Pull request closed without merging**
