### PR TITLE
Changing the top banner if a version is deprecated

### PR DESCRIPTION
**Pull request by samuele-mattiuzzo**
To not be merged yet

### CODE REVIEW

**Comment by andylolz** [comment]
I added a new feature to referencebot, in case it is useful…

@referencebot: Build version 1.05.

**Comment by samuele-mattiuzzo** [comment]
@andylolz that's great, although we now have http://dev.reference.iatistandard.org/ that already has those changes deployed (it's only internal and certain links still go to the main reference site because statically built and all)

**Comment by andylolz** [comment]
It looks like dev.reference.iatistandard.org currently includes IATI/IATI-Guidance#340, too, so I guess it was deployed manually.

referencebot allows any PR to be tested without any need for a techie. The built sites live at unique(ish) URLs, so you can have more than one at once.

**Comment by samuele-mattiuzzo** [comment]
> It looks like dev.reference.iatistandard.org currently includes [IATI/IATI-Guidance#340](https://github.com/IATI/IATI-Guidance/pull/340), too, so I guess it was deployed manually.
> 

more or less, but yes, it does obviously include it as we needed to test it in our internal `dev` instance that we use exactly for this above here purpose :)

**Comment by andylolz** [comment]
Yes, understood. Wasn’t a criticism. I just meant that referencebot attempts to solve a slightly different problem.

**Pull request merged**
