### PR TITLE
add redirects to iatistandard.org

### PR DESCRIPTION
**Pull request by Ocre42**
Shutting down aidtransparency.net, setting up the redirects for anything referencing to the old site to match to the new website.

### CODE REVIEW

**Comment by andylolz** [comment]
Everything in this folder refers to reference.iatistandard.org. The folder is called /iatistandard for historic reasons (because reference.iatistandard.org used to live at iatistandard.org). The redirects in this folder all live on the reference.iatistandard.org server, and redirect _from_ there.

This new file refers to redirects from aidtransparency.net. None of them go to reference.iatistandard.org, so it’s unrelated to that. I wonder if this could be made clearer, either by housing the file somewhere else, or naming it accordingly?

**Comment by samuele-mattiuzzo** [comment]
> I wonder if this could be made clearer, either by housing the file somewhere else, or naming it accordingly?

Renaming it was under discussion internally, so yeah, it was already in progress :)

The file can live in here, finding it a new home wasn't and isn't priority at the moment, but we'll consider it

**Comment by andylolz** [comment]
> Renaming it was under discussion internally, so yeah, it was already in progress :)

Great – We’re on the same page then. Though I don’t understand why the PR was approved.

> finding it a new home wasn't and isn't priority at the moment, but we'll consider it

Fair enough.

**Comment by samuele-mattiuzzo** [comment]
> Great – We’re on the same page then. Though I don’t understand why the PR was approved. I only commented after it was approved.

The PR was approved because of internal reasons, since we had to run a tight schedule to switch aidtransparency off and being nitpicky was not important.

**Pull request merged**
