### PR TITLE
Remove version specification from redirects

### PR DESCRIPTION
**Pull request by allthatilk**

### CODE REVIEW

**Comment by andylolz** [comment]
Okay, so I’m pretty certain this one will result in a redirect loop. E.g. let’s say I visit /105/guidance/datastore/. Then:

/105/guidance/datastore/ -> /guidance/datastore/ (via line 50)
/guidance/datastore/ -> /203/guidance/datastore/ (via redirects-root.conf)
/203/guidance/datastore/ -> /guidance/datastore/ (via line 50)
/guidance/datastore/ -> /203/guidance/datastore/ (via redirects-root.conf)
/203/guidance/datastore/ -> /guidance/datastore/ (via line 50)
/guidance/datastore/ -> /203/guidance/datastore/ (via redirects-root.conf)
/203/guidance/datastore/ -> /guidance/datastore/ (via line 50)
/guidance/datastore/ -> /203/guidance/datastore/ (via redirects-root.conf)

…etc.

**Comment by andylolz** [comment]
My suggestion would be to remove these redirects completely. I’m not sure what their goal is.

**Comment by allthatilk** [comment]
@andylolz They need to exist but without the version numbers. For example: https://iatistandard.org/guidance/datastore/#alpha-status doesn't work

**Comment by allthatilk** [comment]
There was just some confusion over the info we were given for the ones that don't work and I didn't check stuff properly because I've got ten thousand things to do before I leave on Friday and my brain is fried.

**Comment by andylolz** [comment]
Aha, gotcha!

Okay so I think the consistent approach would then be to add `'guidance/datastore'` to this list:
https://github.com/IATI/preview-website/blob/1f13b52026fc556091b1c104525b11050ed9a7ed/iati/iati/urls.py#L27

…since these redirects are currently all handled there.

**Comment by allthatilk** [comment]
A bunch of redirects to reference aren't handled there for various reasons. The existing setup is already confusing but in the future this will all be scrapped when we're only serving the reference content via the new website. This work is pending the priorities set during the tech audit though so this will do for now.

**Comment by andylolz** [comment]
> A bunch of redirects to reference aren't handled there for various reasons. 

Other than these ones? I wasn’t able to find any others. https://github.com/IATI/IATI-Websites/blob/eb22edb309d7d1dcce5e0f57a1e7c253c3d792c2/iatistandard/redirects.conf#L297-L316

> this will do for now.

Yeah fair enough!

**Pull request merged**
