### PR TITLE
Relative path to assets (fixes missing dropdown arrows in sidebar bug)

### PR DESCRIPTION
**Pull request by andylolz**
Instead of linking to some other server for these assets, fetch them locally.

### CODE REVIEW

**Comment by dalepotter** [comment]
Thanks for this @andylolz - I regenerated the site locally using this branch and unfortunately this made the icons give 404s disappear, for example on the reference page:
image

In light of recent changes to the structure of the URLs, we've made a quick fix in https://github.com/IATI/IATI-Websites/pull/200 but we'll hopefully be able to take a look to find a fix for the relative path you proposed when things slow down...

**Comment by andylolz** [comment]
Hi @dalepotter – thanks for reviewing this one. You’re absolutely right, it was totally incorrect! The paths I used were relative to the javascript, instead of the current page.

I’ve revised this PR now, and solved it a different way. Instead of using `img` tags, I’ve put background images on the toggle `<span>`s in CSS. This is a bit cleaner and tidier, and solves the relative path problem.

I’ve checked this in firefox/OSX, Chrome/OSX and safari/OSX and it’s fine on all of those. I guess it’s fine more generally, but probably worth checking.

**Comment by andylolz** [comment]
I think this PR may actually fix #168.

**Comment by andylolz** [comment]
@samuele-mattiuzzo: Bumping this, because it’s possibly useful?

**Comment by andylolz** [comment]
Looks like this PR was closed, but I think this problem has come up again.

Maybe worth revisiting this, @samuele-mattiuzzo?

**Comment by samuele-mattiuzzo** [comment]
@andylolz we're in the middle of taking care of this, thanks for bumping, will consider

**Comment by andylolz** [comment]
> we're in the middle of taking care of this, thanks for bumping, will consider

Looks like this hass been resolved again, but in the same way as before.

Personally, I think it’s preferable for reference.iatistandard.org to be standalone, rather than dependent on some external assets (that live on some other server). This PR would fix that, I think.

**Comment by samuele-mattiuzzo** [comment]
> Personally, I think it’s preferable for reference.iatistandard.org to be standalone, rather than dependent on some external assets (that live on some other server). This PR would fix that, I think.

reference.iatistandard.org will undergo a big re factor to bring it under a common style with iatistandard.org (effectively becoming part of it); as we're still scoping it out, where and how the assets will be used is still an unknown

**Comment by andylolz** [comment]
Kk! I'll bump this PR if the issue comes up again.

**Comment by samuele-mattiuzzo** [comment]
thanks

**Comment by andylolz** [comment]
> Kk! I'll bump this PR if the issue comes up for a fourth time.

It has indeed come up again – this time on http://archivereference.iatistandard.org/:

Screenshot 2020-07-14 at 16 14 41

**Pull request closed without merging**
